name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.8

      - name: Build release
        run: earthly +release --build_type=standalone

      - name: Unpack release
        run: unzip release.zip -d build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
